require("user.lazy")
require("user.keymaps")
require("user.cmp")
require("user.comments")
require("user.pounce")
require("user.colorscheme")
require("user.smoothscrolling")
require("user.tabout")
