require("user.lazy")
require("user.options")
require("user.surround")
require("user.keymaps")

if vim.g.vscode then
    require("user.vscode.options")
    require("user.vscode.smoothscrolling")
    require("user.vscode.treesitter")
else
    require("user.autocmds")
    require("user.cmp")
    require("user.mason")
    require("user.formatter")
    require("user.autopairs")
    require("user.telescope")
    require("user.comments")
    require("user.noice")
    require("user.pounce")
    require("user.harpoon")
    require("user.persisted")
    require("user.nvimtree")
    require("user.colorscheme")
    require("user.reload")
    -- require("user.typescript")
    -- require("user.scrollback")
    require("user.smoothscrolling")
    require("user.illuminate")
    require("user.pounce")
    require("user.treesitter")
    require("user.autopairs")
    require("user.tabout")
    require("user.git")
end
