return {
	-- "tomasiser/vim-code-dark",
	-- priority = 1000,
	-- event = "BufReadPre",
	-- config = function()
	-- 	vim.g["codedark_term256"] = 1
	-- 	vim.cmd([[
	-- 		colorscheme codedark
	-- 		hi Comment guifg=#dbaf84
	-- 		hi String guifg=#efa29b
	-- 		" hi! link Sneak Search
	-- 		" hi Search guibg=#658da1
	-- 		hi! illuminatedWordText cterm=underline gui=underline
	-- 		let g:sneak#label = 1
	-- 		hi IncSearch guibg=#658da1
	-- 		hi NoiceCmdlinePopupBorderSearch guifg=#9cdcfe
	-- 		hi NoiceCmdlineIconSearch guifg=#9cdcfe
	-- 		hi! EasyMotionTarget guifg=#9cdcfe ctermfg=blue
	-- 		hi! EasyMotionShade ctermbg=none ctermfg=none
	-- 		hi! EasyMotionIncSearch guifg=#9cdcfe ctermfg=blue
	-- 		highlight NvimDapVirtualText guibg=#232323 guifg=#efa29b
	-- 		let g:EasyMotion_enter_jump_first = 1
	-- 		let g:EasyMotion_space_jump_first = 1
	-- 		let g:EasyMotion_verbose = 0
	--   	]])
	-- end,
}
